'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.17929
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("hdd_guardian.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property add_virtual() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_virtual", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property all_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("all_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property border() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("border", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a HDD Guardian 0.6.0  ==
        '''	new:
        '''	- added support for multiple docking USB devices;
        '''	- added support for Dell PERC H200 controller (thanks to Brian Elias);
        '''	- added support for Microsoft Windows 8 Storage Spaces Controller (thanks to Ouellette Edward J.);
        '''	- is possible to disable support for Intel Matrix (avoid sound stuttering for systems without RAID);
        '''	- package now include smartctl 6.2;
        '''	- package include bulgarian translation;
        '''	- redesigned interface;
        '''	- resizable window;
        '''	- add capability to se [stringa troncata]&quot;;.
        '''</summary>
        Public ReadOnly Property Changelog() As String
            Get
                Return ResourceManager.GetString("Changelog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;table&gt;
        '''  &lt;!--BASIC EMPTY BLOCK--&gt;
        '''  &lt;!--
        '''  &lt;attribute smartctl=&quot;&quot; group=&quot;&quot;&gt;
        '''    &lt;name&gt;&lt;/name&gt;
        '''    &lt;description&gt;&lt;/description&gt;
        '''  &lt;/attribute&gt;
        '''  --&gt;
        '''  
        '''  &lt;attribute smartctl=&quot;Dummy&quot; group=&quot;Generic&quot;&gt;
        '''    &lt;name&gt;Unknown&lt;/name&gt;
        '''    &lt;description&gt;No informations for this attribute.&lt;/description&gt;
        '''  &lt;/attribute&gt;
        '''  &lt;attribute smartctl=&quot;Not_Supported&quot; group=&quot;Generic&quot;&gt;
        '''    &lt;name&gt;Attribute not supported&lt;/name&gt;
        '''    &lt;description&gt;This attribute is not supported by this [stringa troncata]&quot;;.
        '''</summary>
        Public ReadOnly Property dafault_attributes() As String
            Get
                Return ResourceManager.GetString("dafault_attributes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;interface&gt;
        '''  &lt;!-- &lt;string id=&quot;&quot; text=&quot;&quot;/&gt; --&gt;
        '''  &lt;info language=&quot;English&quot; translator=&quot;Parise Samuele&quot; version=&quot;0.6.0&quot;/&gt;
        '''  &lt;group id=&quot;00&quot; title=&quot;Main menu&quot;&gt;
        '''	  &lt;string id=&quot;01&quot; text=&quot;Overview&quot;/&gt;
        '''	  &lt;string id=&quot;02&quot; text=&quot;Manage&quot;/&gt;
        '''	  &lt;string id=&quot;03&quot; text=&quot;System&quot;/&gt;
        '''    &lt;string id=&quot;04&quot; text=&quot;Debug&quot;/&gt;
        '''	  &lt;string id=&quot;10&quot; text=&quot;File&quot;/&gt;
        '''	  &lt;string id=&quot;11&quot; text=&quot;Settings&quot;/&gt;
        '''	  &lt;string id=&quot;12&quot; text=&quot;About&quot;/&gt;
        '''	  &lt;string id=&quot;13&quot; text=&quot;Exit&quot;/&gt;
        '''  &lt;/group&gt;
        '''  &lt;group id= [stringa troncata]&quot;;.
        '''</summary>
        Public ReadOnly Property default_interface() As String
            Get
                Return ResourceManager.GetString("default_interface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property device_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("device_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property device_harddisk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("device_harddisk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property device_partition() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("device_partition", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property devices_tray_icons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("devices_tray_icons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property devices_tray_icons_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("devices_tray_icons_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property document_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("document_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property drive_error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drive_error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property drive_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("drive_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property failed_inthepast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("failed_inthepast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property failed_never() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("failed_never", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property failed_now() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("failed_now", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property failed_unknown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("failed_unknown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property failed_warning() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("failed_warning", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Mozilla Public License Version 2.0
        '''==================================
        '''
        '''1. Definitions
        '''--------------
        '''
        '''1.1. &quot;Contributor&quot;
        '''    means each individual or legal entity that creates, contributes to
        '''    the creation of, or owns Covered Software.
        '''
        '''1.2. &quot;Contributor Version&quot;
        '''    means the combination of the Contributions of others (if any) used
        '''    by a Contributor and that particular Contributor&apos;s Contribution.
        '''
        '''1.3. &quot;Contribution&quot;
        '''    means Covered Software of a particular Contributor.
        '''
        '''1.4. &quot;Cove [stringa troncata]&quot;;.
        '''</summary>
        Public ReadOnly Property License() As String
            Get
                Return ResourceManager.GetString("License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property loader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property loader2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loader2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pc_game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pc_game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pc_laptop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pc_laptop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pc_office() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pc_office", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a 12.
        '''</summary>
        Public ReadOnly Property prerelease() As String
            Get
                Return ResourceManager.GetString("prerelease", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;private&gt;
        '''	&lt;mail&gt;notifications.hddguardian@gmail.com&lt;/mail&gt;
        '''	&lt;password&gt;3ru357an&lt;/password&gt;
        '''	&lt;key&gt;f801babd2bc60f74&lt;/key&gt;
        '''	&lt;iv&gt;2aacef3a7a5af6d3&lt;/iv&gt;
        '''&lt;/private&gt;.
        '''</summary>
        Public ReadOnly Property privatedata() As String
            Get
                Return ResourceManager.GetString("privatedata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property r0_star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r0_star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property r1_star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r1_star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property r2_star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r2_star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property r3_star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r3_star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property r4_star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r4_star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property r5_star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r5_star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Raptor_X() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Raptor_X", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property rescan_usb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rescan_usb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property some_problems() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("some_problems", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property ssd_tray_icons() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ssd_tray_icons", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property update_ko() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_ko", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property update_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("update_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property view_refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property worldflag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("worldflag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property XCraft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("XCraft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
