'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.17929
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funzionalità di salvataggio automatico My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property StartMinimized() As Boolean
            Get
                Return CType(Me("StartMinimized"),Boolean)
            End Get
            Set
                Me("StartMinimized") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MinimizeOnTray() As Boolean
            Get
                Return CType(Me("MinimizeOnTray"),Boolean)
            End Get
            Set
                Me("MinimizeOnTray") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CloseOnTray() As Boolean
            Get
                Return CType(Me("CloseOnTray"),Boolean)
            End Get
            Set
                Me("CloseOnTray") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AlwaysShowTrayIcon() As Boolean
            Get
                Return CType(Me("AlwaysShowTrayIcon"),Boolean)
            End Get
            Set
                Me("AlwaysShowTrayIcon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ConfirmOnExit() As Boolean
            Get
                Return CType(Me("ConfirmOnExit"),Boolean)
            End Get
            Set
                Me("ConfirmOnExit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property DataUpdate() As Short
            Get
                Return CType(Me("DataUpdate"),Short)
            End Get
            Set
                Me("DataUpdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ImminentFailure() As Boolean
            Get
                Return CType(Me("ImminentFailure"),Boolean)
            End Get
            Set
                Me("ImminentFailure") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TemperatureThreshold() As Boolean
            Get
                Return CType(Me("TemperatureThreshold"),Boolean)
            End Get
            Set
                Me("TemperatureThreshold") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ReallocatedSector() As Boolean
            Get
                Return CType(Me("ReallocatedSector"),Boolean)
            End Get
            Set
                Me("ReallocatedSector") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SpinRetry() As Boolean
            Get
                Return CType(Me("SpinRetry"),Boolean)
            End Get
            Set
                Me("SpinRetry") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Temperature() As Boolean
            Get
                Return CType(Me("Temperature"),Boolean)
            End Get
            Set
                Me("Temperature") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ReallocatedEvent() As Boolean
            Get
                Return CType(Me("ReallocatedEvent"),Boolean)
            End Get
            Set
                Me("ReallocatedEvent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CurrentPendingSector() As Boolean
            Get
                Return CType(Me("CurrentPendingSector"),Boolean)
            End Get
            Set
                Me("CurrentPendingSector") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property OfflineUncorrectable() As Boolean
            Get
                Return CType(Me("OfflineUncorrectable"),Boolean)
            End Get
            Set
                Me("OfflineUncorrectable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SoftReadErrorRate() As Boolean
            Get
                Return CType(Me("SoftReadErrorRate"),Boolean)
            End Get
            Set
                Me("SoftReadErrorRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DiskShift() As Boolean
            Get
                Return CType(Me("DiskShift"),Boolean)
            End Get
            Set
                Me("DiskShift") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property VitalParameters() As Boolean
            Get
                Return CType(Me("VitalParameters"),Boolean)
            End Get
            Set
                Me("VitalParameters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SharingFolder() As String
            Get
                Return CType(Me("SharingFolder"),String)
            End Get
            Set
                Me("SharingFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property ExternalDevicesUpdate() As Short
            Get
                Return CType(Me("ExternalDevicesUpdate"),Short)
            End Get
            Set
                Me("ExternalDevicesUpdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property VirtualDevicesUpdate() As Short
            Get
                Return CType(Me("VirtualDevicesUpdate"),Short)
            End Get
            Set
                Me("VirtualDevicesUpdate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Indilinx() As Boolean
            Get
                Return CType(Me("Indilinx"),Boolean)
            End Get
            Set
                Me("Indilinx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Intel() As Boolean
            Get
                Return CType(Me("Intel"),Boolean)
            End Get
            Set
                Me("Intel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Micron() As Boolean
            Get
                Return CType(Me("Micron"),Boolean)
            End Get
            Set
                Me("Micron") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Samsung() As Boolean
            Get
                Return CType(Me("Samsung"),Boolean)
            End Get
            Set
                Me("Samsung") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SandForce() As Boolean
            Get
                Return CType(Me("SandForce"),Boolean)
            End Get
            Set
                Me("SandForce") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ExportToXml() As Boolean
            Get
                Return CType(Me("ExportToXml"),Boolean)
            End Get
            Set
                Me("ExportToXml") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property XmlFolder() As String
            Get
                Return CType(Me("XmlFolder"),String)
            End Get
            Set
                Me("XmlFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AreSettingsUpgraded() As Boolean
            Get
                Return CType(Me("AreSettingsUpgraded"),Boolean)
            End Get
            Set
                Me("AreSettingsUpgraded") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EnableRating() As Boolean
            Get
                Return CType(Me("EnableRating"),Boolean)
            End Get
            Set
                Me("EnableRating") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property EnableTune() As Boolean
            Get
                Return CType(Me("EnableTune"),Boolean)
            End Get
            Set
                Me("EnableTune") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property TuneErrors() As Short
            Get
                Return CType(Me("TuneErrors"),Short)
            End Get
            Set
                Me("TuneErrors") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property Tune197() As Short
            Get
                Return CType(Me("Tune197"),Short)
            End Get
            Set
                Me("Tune197") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property Tune198() As Short
            Get
                Return CType(Me("Tune198"),Short)
            End Get
            Set
                Me("Tune198") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CheckUpdates() As Boolean
            Get
                Return CType(Me("CheckUpdates"),Boolean)
            End Get
            Set
                Me("CheckUpdates") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property TempFahrenheit() As Boolean
            Get
                Return CType(Me("TempFahrenheit"),Boolean)
            End Get
            Set
                Me("TempFahrenheit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MonitorUsb() As Boolean
            Get
                Return CType(Me("MonitorUsb"),Boolean)
            End Get
            Set
                Me("MonitorUsb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CustomTemperature() As Boolean
            Get
                Return CType(Me("CustomTemperature"),Boolean)
            End Get
            Set
                Me("CustomTemperature") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("50")>  _
        Public Property CustomTemperatureValue() As Short
            Get
                Return CType(Me("CustomTemperatureValue"),Short)
            End Get
            Set
                Me("CustomTemperatureValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IgnoreCsmi() As Boolean
            Get
                Return CType(Me("IgnoreCsmi"),Boolean)
            End Get
            Set
                Me("IgnoreCsmi") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MultiDock() As Boolean
            Get
                Return CType(Me("MultiDock"),Boolean)
            End Get
            Set
                Me("MultiDock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property WarningTemp() As Boolean
            Get
                Return CType(Me("WarningTemp"),Boolean)
            End Get
            Set
                Me("WarningTemp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningReallocatedEvent() As Boolean
            Get
                Return CType(Me("WarningReallocatedEvent"),Boolean)
            End Get
            Set
                Me("WarningReallocatedEvent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningCurrentPendingSector() As Boolean
            Get
                Return CType(Me("WarningCurrentPendingSector"),Boolean)
            End Get
            Set
                Me("WarningCurrentPendingSector") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningOfflineUncorrectable() As Boolean
            Get
                Return CType(Me("WarningOfflineUncorrectable"),Boolean)
            End Get
            Set
                Me("WarningOfflineUncorrectable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningSoftReadErrorRate() As Boolean
            Get
                Return CType(Me("WarningSoftReadErrorRate"),Boolean)
            End Get
            Set
                Me("WarningSoftReadErrorRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningDiskShift() As Boolean
            Get
                Return CType(Me("WarningDiskShift"),Boolean)
            End Get
            Set
                Me("WarningDiskShift") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningIndilinx() As Boolean
            Get
                Return CType(Me("WarningIndilinx"),Boolean)
            End Get
            Set
                Me("WarningIndilinx") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningIntel() As Boolean
            Get
                Return CType(Me("WarningIntel"),Boolean)
            End Get
            Set
                Me("WarningIntel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningMicron() As Boolean
            Get
                Return CType(Me("WarningMicron"),Boolean)
            End Get
            Set
                Me("WarningMicron") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningSamsung() As Boolean
            Get
                Return CType(Me("WarningSamsung"),Boolean)
            End Get
            Set
                Me("WarningSamsung") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningSandForce() As Boolean
            Get
                Return CType(Me("WarningSandForce"),Boolean)
            End Get
            Set
                Me("WarningSandForce") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RememberWindowSize() As Boolean
            Get
                Return CType(Me("RememberWindowSize"),Boolean)
            End Get
            Set
                Me("RememberWindowSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property WindowSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("WindowSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("WindowSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MailSend() As Boolean
            Get
                Return CType(Me("MailSend"),Boolean)
            End Get
            Set
                Me("MailSend") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property MailDestination() As String
            Get
                Return CType(Me("MailDestination"),String)
            End Get
            Set
                Me("MailDestination") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MailTemperature() As Boolean
            Get
                Return CType(Me("MailTemperature"),Boolean)
            End Get
            Set
                Me("MailTemperature") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MailFail() As Boolean
            Get
                Return CType(Me("MailFail"),Boolean)
            End Get
            Set
                Me("MailFail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MailReliability() As Boolean
            Get
                Return CType(Me("MailReliability"),Boolean)
            End Get
            Set
                Me("MailReliability") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AutomaticTranslation() As Boolean
            Get
                Return CType(Me("AutomaticTranslation"),Boolean)
            End Get
            Set
                Me("AutomaticTranslation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Language() As String
            Get
                Return CType(Me("Language"),String)
            End Get
            Set
                Me("Language") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ComputerType() As String
            Get
                Return CType(Me("ComputerType"),String)
            End Get
            Set
                Me("ComputerType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningReallocatedSector() As Boolean
            Get
                Return CType(Me("WarningReallocatedSector"),Boolean)
            End Get
            Set
                Me("WarningReallocatedSector") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property WarningSpinRetry() As Boolean
            Get
                Return CType(Me("WarningSpinRetry"),Boolean)
            End Get
            Set
                Me("WarningSpinRetry") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Tolerance() As Boolean
            Get
                Return CType(Me("Tolerance"),Boolean)
            End Get
            Set
                Me("Tolerance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ToleranceLevel() As String
            Get
                Return CType(Me("ToleranceLevel"),String)
            End Get
            Set
                Me("ToleranceLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PowerMode() As Boolean
            Get
                Return CType(Me("PowerMode"),Boolean)
            End Get
            Set
                Me("PowerMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PowerModeLevel() As String
            Get
                Return CType(Me("PowerModeLevel"),String)
            End Get
            Set
                Me("PowerModeLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Maximized() As Boolean
            Get
                Return CType(Me("Maximized"),Boolean)
            End Get
            Set
                Me("Maximized") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Debug() As Boolean
            Get
                Return CType(Me("Debug"),Boolean)
            End Get
            Set
                Me("Debug") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CustomServer() As Boolean
            Get
                Return CType(Me("CustomServer"),Boolean)
            End Get
            Set
                Me("CustomServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServerLogin() As String
            Get
                Return CType(Me("ServerLogin"),String)
            End Get
            Set
                Me("ServerLogin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServerPassword() As String
            Get
                Return CType(Me("ServerPassword"),String)
            End Get
            Set
                Me("ServerPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServerHost() As String
            Get
                Return CType(Me("ServerHost"),String)
            End Get
            Set
                Me("ServerHost") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ServerPort() As String
            Get
                Return CType(Me("ServerPort"),String)
            End Get
            Set
                Me("ServerPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ServerUseSsl() As Boolean
            Get
                Return CType(Me("ServerUseSsl"),Boolean)
            End Get
            Set
                Me("ServerUseSsl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property InfoPanel() As Boolean
            Get
                Return CType(Me("InfoPanel"),Boolean)
            End Get
            Set
                Me("InfoPanel") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.hdd_guardian.My.MySettings
            Get
                Return Global.hdd_guardian.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
