'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.17929
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("translationtool.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property applications_development_translation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("applications_development_translation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;cultures&gt;
        '''  &lt;item culture=&quot;af-ZA&quot; zone=&quot;Afrikaans - South Africa&quot;/&gt;
        '''  &lt;item culture=&quot;ar&quot; zone=&quot;Generic arabic&quot;/&gt;
        '''  &lt;item culture=&quot;ar-DZ&quot; zone=&quot;Arabic - Algeria&quot;/&gt;
        '''  &lt;item culture=&quot;ar-BH&quot; zone=&quot;Arabic - Bahrain&quot;/&gt;
        '''  &lt;item culture=&quot;ar-EG&quot; zone=&quot;Arabic - Egypt&quot;/&gt;
        '''  &lt;item culture=&quot;ar-IQ&quot; zone=&quot;Arabic - Iraq&quot;/&gt;
        '''  &lt;item culture=&quot;ar-JO&quot; zone=&quot;Arabic - Jordan&quot;/&gt;
        '''  &lt;item culture=&quot;ar-KW&quot; zone=&quot;Arabic - Kuwait&quot;/&gt;
        '''  &lt;item culture=&quot;ar-LB&quot; zone=&quot;Arabic - Lebanon&quot;/&gt;
        '''  &lt;i [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property cultures() As String
            Get
                Return ResourceManager.GetString("cultures", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;table&gt;
        '''  &lt;!--BASIC EMPTY BLOCK--&gt;
        '''  &lt;!--
        '''  &lt;attribute smartctl=&quot;&quot; group=&quot;&quot;&gt;
        '''    &lt;name&gt;&lt;/name&gt;
        '''    &lt;description&gt;&lt;/description&gt;
        '''  &lt;/attribute&gt;
        '''  --&gt;
        '''  
        '''  &lt;attribute smartctl=&quot;Dummy&quot; group=&quot;Generic&quot;&gt;
        '''    &lt;name&gt;Unknown&lt;/name&gt;
        '''    &lt;description&gt;No informations for this attribute.&lt;/description&gt;
        '''  &lt;/attribute&gt;
        '''  &lt;attribute smartctl=&quot;Not_Supported&quot; group=&quot;Generic&quot;&gt;
        '''    &lt;name&gt;Attribute not supported&lt;/name&gt;
        '''    &lt;description&gt;This attribute is not supported by this [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property default_attributes() As String
            Get
                Return ResourceManager.GetString("default_attributes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;interface&gt;
        '''  &lt;!-- &lt;string id=&quot;&quot; text=&quot;&quot;/&gt; --&gt;
        '''  &lt;info language=&quot;English&quot; translator=&quot;Parise Samuele&quot; version=&quot;4.0&quot;/&gt;
        '''  &lt;group id=&quot;00&quot; title=&quot;Main menu&quot;&gt;
        '''	  &lt;string id=&quot;01&quot; text=&quot;Overview&quot;/&gt;
        '''	  &lt;string id=&quot;02&quot; text=&quot;Manage&quot;/&gt;
        '''	  &lt;string id=&quot;03&quot; text=&quot;System&quot;/&gt;
        '''	  &lt;string id=&quot;10&quot; text=&quot;File&quot;/&gt;
        '''	  &lt;string id=&quot;11&quot; text=&quot;Settings&quot;/&gt;
        '''	  &lt;string id=&quot;12&quot; text=&quot;About&quot;/&gt;
        '''	  &lt;string id=&quot;13&quot; text=&quot;Exit&quot;/&gt;
        '''  &lt;/group&gt;
        '''  &lt;group id=&quot;01&quot; title=&quot;Device context menu&quot;&gt;
        '''	   [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property default_interface() As String
            Get
                Return ResourceManager.GetString("default_interface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property info() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("info", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property view_remove() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("view_remove", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
